apiVersion: apps/v1
kind: Deployment
metadata:
  name: resumebuilderbackend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: resumebuilderbackend
  template:
    metadata:
      labels:
        app: resumebuilderbackend
    spec:
      containers:
      - name: resume-builder-be-k8s
        image: suraj2143/resume-builder-be:49
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 4292
